name: 'sales_dw_pipeline'
version: '1.0.0'
profile: 'sales_dw_pipeline'

model-paths:    ["models"]
analysis-paths: ["analyses"]
test-paths:     ["tests"]
seed-paths:     ["seeds"]
macro-paths:    ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  sales_dw_pipeline:
    staging:
      +materialized: view
      # quarantine logic lives inside stg_sales.sql itself via the macro
      # no pre-hooks needed here

    marts:
      +materialized: table
      +schema: warehouse